# Generated by Django 3.2.6 on 2021-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_category', models.CharField(max_length=100)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('book_description', models.TextField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
