# Generated by Django 3.2.6 on 2021-09-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_book_tmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.CharField(max_length=200),
        ),
    ]
